version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
  frontend:
    build: ./client
    ports:
      - "3001:80"
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: AdminPassword123
      MYSQL_DATABASE: mariadb
    ports:
      - "3306:3306"
